version: 0.7.4-{build}
configuration:
- Release
- Debug
platform:
- Any CPU
os: Windows Server 2012 R2
build:
  project: DokanNet.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - reports@islog.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
